### ISSUE TITLE
Why are there so many packages installed along with this one?

### ISSUE THREAD

**Issue by sheam** [chadly/Geocoding.net#107] opened 2018-10-22 06:29 UTC
Installed this nuget package installs about 40 packages along side of it. It seems that most of them are safe to remove. Why are there so many dependancies?

**Comment by chadly** [comment] 2018-10-22 14:01
See here: https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies

I'm going to close this as a dupe of #106.

**Closed by chadly** 2018-10-22 14:01 UTC
